overrides:
  '@tanstack/history': link:../router/packages/history
  '@tanstack/router-core': link:../router/packages/router-core
  '@tanstack/router-devtools-core': link:../router/packages/router-devtools-core
  '@tanstack/vue-router': link:../router/packages/vue-router
  '@tanstack/vue-router-devtools': link:../router/packages/vue-router-devtools
