/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PalsPalIdRouteImport } from './routes/pals/$palId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalsPalIdRoute = PalsPalIdRouteImport.update({
  id: '/pals/$palId',
  path: '/pals/$palId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pals/$palId': typeof PalsPalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pals/$palId': typeof PalsPalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pals/$palId': typeof PalsPalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pals/$palId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pals/$palId'
  id: '__root__' | '/' | '/pals/$palId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalsPalIdRoute: typeof PalsPalIdRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pals/$palId': {
      id: '/pals/$palId'
      path: '/pals/$palId'
      fullPath: '/pals/$palId'
      preLoaderRoute: typeof PalsPalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalsPalIdRoute: PalsPalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
